services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres
  redis:
    image: "redis:alpine"
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - "6379"
    container_name: redis
  postgres:
    image: postgres
    command: -p 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "SHAHOVPOBEDA"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: postgres